name: http-mock-plugin
description: http mock plugin
display-name: http-mock-plugin
picture: plugin.png
category: Backend # Ref: https://docs.stackspot.com/docs/create-stacks/yaml-files/plugin/#category
compatibility:
  - javascript
  - typescript
  - angular
  - react
about: docs/about.md
usage: docs/usage.md
use-case: docs/use-case.md
implementation: docs/implementation.md
technologies: # Ref: https://docs.stackspot.com/docs/create-stacks/yaml-files/yaml/#technologies
  ["Web", "Typescript"]
types:
  - app

hooks:
  - type: run
    trigger: after-render
    commands:
      - "npm install --save-dev @hapi/hapi nodemon"

  - type: edit
    trigger: after-render
    path: ./package.json
    changes:
      - search:
          string: 'scripts'
          insert-after: 
            value: |
                  "stub": "nodemon ./stub/index.js",

